_wandb:
    value:
        cli_version: 0.22.3
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 50
            "3":
                - 13
                - 15
                - 16
            "4": 3.13.2
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
debug:
    value: false
trainer:
    value:
        _target_: test_composite_function.test_composite_function
        cfg:
            batch_size: 128
            dropout: 0.1
            flipping_subsets:
                - - 0
                - - 1
            function_dim: 12
            learning_rate: 0.0001
            max_steps: 10000
            n_embd: 64
            n_heads: 1
            n_layers: 2
            target_function_string: 1.0x0x1 + 1.0x1x2
            vocab_size: 3
wandb_config:
    value:
        name: composite-function-test
        notes: Testing composite function with CoT
        project: distributional-cot
        tags:
            - train
